name: John Laney
favicon: null
layout_spectrum: 0.5242991412524134
typography_spectrum: 0.5708442104514688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9465110821183771
  lightness: 0.602732757339254
  saturation: 0.8060797322541475
  rhythmicContrast: 0.5957066565752029
purpose: []
